<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products =[
            [
                'name' => '3 Bottle Set - Mix',
                'description' => 'Premium Lager、Pale Ale、Belgian Blonde',
                'category' => 'Special Package',
                'nickname' => '3 Bottle Set - Mix',
		        'name_slug' => '3-bottle-set-mix',
		        'category_slug' => 'special-package',
                'ABV' => 'Varies',
                'ingredients' => 'Varies in each bottle',
                'stock' => 10,
                'picture' => 'resources\images\product\package3mix.png',
                'price' => 2040,
            ],
            [
                'name' => '3 Bottle Set - Belgian Beer',
                'description' => 'Belgian Blonde, Belgian White, Strawberry Ale',
                'category' => 'Special Package',
		        'nickname' => '3 Bottle Set - Belgian Beer',
		        'name_slug' => '3-bottle-set-belgian-beer',
		        'category_slug' => 'special-package',
                'ABV' => 'Varies',
                'ingredients' => 'Varies in each bottle',
                'stock' => 10,
                'picture' => 'resources\images\product\package3belgian.png',
                'price' => 2040,
            ],
            [
                'name' => '6 Bottle Set',
                'description' => 'Nikko Monkeys : Premium Lager, Pale Ale <br> Nikko Belgian Beer : Belgian Blonde, Belgian White, Strawberry Ale, Yuzu Saison',
                'category' => 'Special Package',
		        'nickname' => '6 Bottle Set',
		        'name_slug' => '6-bottle-set',
		        'category_slug' => 'special-package',
                'ABV' => 'Varies',
                'ingredients' => 'Varies in each bottle',
                'stock' => 10,
                'picture' => 'resources\images\product\package6mix.png',
                'price' => 3640,
            ],
            [
                'name' => 'Nikko Belgian Beer',
                'description' => '2本セット ベルジャンシリーズ',
                'category' => 'Special Package',
		        'nickname' => 'Nikko Belgian Beer',
		        'name_slug' => 'nikko-belgian-beer',
		        'category_slug' => 'special-package',
                'ABV' => 'Varies',
                'ingredients' => 'Varies in each bottle',
                'stock' => 10,
                'picture' => 'resources\images\product\package2belgian.png',
                'price' => 1380,
            ],
            [
                'name' => 'Nikko Monkeys',
                'description' => '2本セット モンキーズシリーズ',
                'category' => 'Special Package',
		        'nickname' => 'Nikko Monkeys',
		        'name_slug' => 'nikko-monkeys',
		        'category_slug' => 'special-package',
                'ABV' => '4%',
                'ingredients' => '4%',
                'stock' => 10,
                'picture' => 'resources\images\product\packagemonkey.png',
                'price' => 1380,
            ],
            [
                'name' => 'été - Sansho Saison',
                'description' => '奥日光で採れた山椒の新葉飲みを使用した香り高いハーブセゾン 山椒の新葉を感じていただけるよう、フルーティでグラッシーな厳選ホップを 使用し、飲み口がドライながらも、 芳香なアロマを感じられるように致しました。',
                'category' => 'Nikko Belgian Beer',
		        'nickname' => 'Sansho Saison',
		        'name_slug' => 'sansho-saishon',
		        'category_slug' => 'nikko-belgian-beer',
                'ABV' => '6%',
                'ingredients' => '・山椒・ホップ',
                'stock' => 10,
                'picture' => 'resources\images\product\belgiansanshosaison.png',
                'price' => 440,
            ],
            [
                'name' => 'Hiver - Yuzu Saison',
                'description' => '宇都宮産の宮柚子を使用したベルジャン・フルーツビールです。 使用する柚子は単細胞溶液加工にて一次加工を行い、柚子本来の風味と苦味 を表現したビールです。',
                'category' => 'Nikko Belgian Beer',
		        'nickname' => 'Yuzu Saison',
		        'name_slug' => 'yuzu-saison',
		        'category_slug' => 'nikko-belgian-beer',
                'ABV' => '5.5%',
                'ingredients' => '・ゆず果汁・ホップ',
                'stock' => 10,
                'picture' => 'resources\images\product\belgianyuzusaison.png',
                'price' => 550,
            ],
            [
                'name' => 'Trois - Strawberry Ale',
                'description' => 'いちごを原料全体の75%以上使用。苺本来の持つ程よい酸味を活かした、まるで 甘酸っぱいをかじったようなちょっぴりビターテイストのフルーツビール',
                'category' => 'Nikko Belgian Beer',
		        'nickname' => 'Strawberry Ale',
		        'name_slug' => 'strawberry-ale',
		        'category_slug' => 'nikko-belgian-beer',
                'ABV' => '4.5%',
                'ingredients' => '・麦芽・ホップ',
                'stock' => 10,
                'picture' => 'resources\images\product\belgianstrawberryale.png',
                'price' => 550,
            ],
            [
                'name' => 'Deux - Belgian white',
                'description' => '小麦由来の滑らかな口当たりと爽やかな酸味・フルーティなアロマが特徴のベルジャ ンスタイルビール。コリアンダーシードとオレンジピールによるスパイシーなアクセントが 全体を引き締めて心地よい風味をもたらしている。',
                'category' => 'Nikko Belgian Beer',
		        'nickname' => 'Belgian White',
		        'name_slug' => 'belgian-white',
		        'category_slug' => 'nikko-belgian-beer',
                'ABV' => '5%',
                'ingredients' => '・ホップ・オレンジビール・コリアンダシード',
                'stock' => 10,
                'picture' => 'resources\images\product\belgianwhite.png',
                'price' => 440,
            ],
            [
                'name' => 'Un - Belgian Blonde',
                'description' => 'バナナや洋梨のようなフルーティーなアロマとベルジャンスタイル特有の風味が融合し 上品で複雑な香りに誘われる。モルト由来のコク・爽やかな酸味を有し、 バランスのとれた味わい。',
                'category' => 'Nikko Belgian Beer',
		        'nickname' => 'Belgian Blonde',
		        'name_slug' => 'belgian-blonde',
		        'category_slug' => 'nikko-belgian-beer',
                'ABV' => '6%',
                'ingredients' => '・ホップ・ハーブスパイス・糖類',
                'stock' => 10,
                'picture' => 'resources\images\product\belgianblonde.png',
                'price' => 440,
            ],
            [
                'name' => 'Premium Lager',
                'description' => '口当たりはモルト由来の芳醇なコクと甘みが感じられ、ザーツホップの華やかなアロ マと上品な苦味が全体の調和を取ります。ビルスナースタイルのピールです。',
                'category' => 'The Nikko Monkeys',
		        'nickname' => 'Premium Lager',
		        'name_slug' => 'premium-lager',
		        'category_slug' => 'the-nikko-monkeys',
                'ABV' => '5%',
                'ingredients' => '・ホップ・ハーブスパイス',
                'stock' => 10,
                'picture' => 'resources\images\product\monkeypremiumlager.png',
                'price' => 690,
            ],
            [
                'name' => 'Pale Ale',
                'description' => 'ホップにシトラとシムコーを贅沢に使用した、パッションフルーツの様なアロマと、 フレッシュな柑橋系のフレーバーが爽やかなアメリカンペールエールです。',
                'category' => 'The Nikko Monkeys',
		        'nickname' => 'Pale Ale',
		        'name_slug' => 'pale-ale',
		        'category_slug' => 'the-nikko-monkeys',
                'ABV' => '4%',
                'ingredients' => '・ホップ・ハーブスパイス',
                'stock' => 10,
                'picture' => 'resources\images\product\monkeypaleale.png',
                'price' => 690,
            ],
        ];
        Product::insert($products);
    }
}